CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "account" (
    "userId" uuid NOT NULL,
    "type" text NOT NULL,
    "provider" text NOT NULL,
    "providerAccountId" text NOT NULL,
    "refresh_token" text,
    "access_token" text,
    "expires_at" integer,
    "token_type" text,
    "scope" text,
    "id_token" text,
    "session_state" text,
    CONSTRAINT "account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "LicitacaoDocumento" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "licitacaoPncpId" text NOT NULL,
    "nomeArquivo" text NOT NULL,
    "textoChunk" text NOT NULL,
    "embedding" vector(768) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PncpLicitacao" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PncpLicitacao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
    "numeroControlePNCP" text NOT NULL,
    "cnpjOrgao" text NOT NULL,
    "orgao" text,
    "anoCompra" integer NOT NULL,
    "sequencialCompra" integer NOT NULL,
    "modalidade" text,
    "numeroProcesso" text,
    "objetoCompra" text NOT NULL,
    "valorEstimado" numeric(19, 2),
    "dataPublicacaoPNCP" timestamp NOT NULL,
    "dataAtualizacao" timestamp NOT NULL,
    "situacao" text,
    "linkSistemaOrigem" text,
    "linkPNCP" text,
    "createdAt" timestamp DEFAULT now(),
    "updatedAt" timestamp,
    "iaResumo" text,
    "iaPalavrasChave" text[],
    "unidadeOrgao" text,
    "municipio" text,
    "uf" text,
    "modoDisputa" text,
    "criterioJulgamento" text,
    "informacaoComplementar" text,
    "aceitaJustificativa" boolean,
    "niSolicitante" text,
    "dataAutorizacao" timestamp,
    "justificativaPresencial" text,
    "grauRelevanciaIA" text,
    "justificativaRelevanciaIA" text,
    CONSTRAINT "PncpLicitacao_numeroControlePNCP_unique" UNIQUE("numeroControlePNCP")
);
--> statement-breakpoint
CREATE TABLE "RelevanciaFeedback" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "voto" integer NOT NULL,
    "userId" uuid NOT NULL,
    "licitacaoPncpId" text NOT NULL,
    "createdAt" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "session" (
    "sessionToken" text PRIMARY KEY NOT NULL,
    "userId" uuid NOT NULL,
    "expires" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "SyncLog" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "SyncLog_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
    "date" timestamp NOT NULL,
    "status" text NOT NULL,
    "startTime" timestamp NOT NULL,
    "endTime" timestamp,
    "recordsFetched" integer DEFAULT 0,
    "errorMessage" text,
    CONSTRAINT "SyncLog_date_unique" UNIQUE("date")
);
--> statement-breakpoint
CREATE TABLE "user" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "name" text,
    "email" text NOT NULL,
    "emailVerified" timestamp,
    "image" text,
    CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verificationToken" (
    "identifier" text NOT NULL,
    "token" text NOT NULL,
    "expires" timestamp NOT NULL,
    CONSTRAINT "verificationToken_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LicitacaoDocumento" ADD CONSTRAINT "LicitacaoDocumento_licitacaoPncpId_PncpLicitacao_numeroControlePNCP_fk" FOREIGN KEY ("licitacaoPncpId") REFERENCES "public"."PncpLicitacao"("numeroControlePNCP") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "RelevanciaFeedback" ADD CONSTRAINT "RelevanciaFeedback_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "RelevanciaFeedback" ADD CONSTRAINT "RelevanciaFeedback_licitacaoPncpId_PncpLicitacao_numeroControlePNCP_fk" FOREIGN KEY ("licitacaoPncpId") REFERENCES "public"."PncpLicitacao"("numeroControlePNCP") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;